### ISSUE TITLE
error about unbound

### ISSUE THREAD

**Issue by kozora** [samwiseg00/zabbix#1]
Hi, there
I install the unboud plugin, and zabbix server can't get value data, log show these error,
` 27868:20171220:101437.536 error reason for "DNS server:unbound.type[ANY]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]
 27872:20171220:101438.538 error reason for "DNS server:unbound.type[A]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]
 27874:20171220:101440.539 error reason for "DNS server:unbound.type[CNAME]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]
 27868:20171220:101441.540 error reason for "DNS server:unbound.type[MX]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]
 27869:20171220:101442.541 error reason for "DNS server:unbound.type[NS]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]
 27872:20171220:101443.542 error reason for "DNS server:unbound.type[PTR]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]
 27868:20171220:101444.544 error reason for "DNS server:unbound.type[SOA]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]
 27868:20171220:101444.544 error reason for "DNS server:unbound.type[SPF]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]
 27869:20171220:101445.544 error reason for "DNS server:unbound.type[SRV]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]
 27874:20171220:101446.545 error reason for "DNS server:unbound.type[TXT]" changed: Received value [0sudo: no tty present and no askpass program specified] is not suitable for value type [Numeric (float)]`

**Comment by samwiseg00** [comment]
what log is this?

**Comment by jcsbarreto** [comment]
When trying to execute the command below I have the following error output:

[root@xxxxx unbound]#  /usr/sbin/unbound-control stats_noreset
[1526047010] unbound-control[29326:0] error: connect: Connection refused for 127.0.0.1

**Comment by samwiseg00** [comment]
Did you make sure unbound is running locally? It seems like unbound-control cannot contact unbound.
