### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by ffkammer** [samwiseg00/zabbix#2]
Hi! I configured the sudo and I imported the template on zabbix server but when I'm receiving an error when running the /usr/sbin/unbound-control command.

The errors are: 

# sudo -u zabbix /usr/sbin/unbound-control stats_noreset
error: Error setting up SSL_CTX client key and cert
139623853516432:error:0200100D:system library:fopen:Permission denied:bss_file.c:398:fopen('/etc/unbound/unbound_control.pem','r')
139623853516432:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
139623853516432:error:140AD002:SSL routines:SSL_CTX_use_certificate_file:system lib:ssl_rsa.c:454:

Can you help me to solve it?

**Comment by samwiseg00** [comment]
did you check SE linux and make sure it is not being denied?
