### ISSUE TITLE
Temperature graph

### ISSUE THREAD

**Issue by maximkrusina** [samwiseg00/zabbix#4]
Hi, I had a nice graph showing a temperature for Synology and then for each disk. But I'm not sure if is it possible to create one graph in Discovery with all the disks temperatures in one graph. I can help :) And thanx!

**Comment by samwiseg00** [comment]
Ya that should not be too hard. I will look into it and let you know when its been updated.

**Comment by maximkrusina** [comment]
I'm using this one...
![image](https://user-images.githubusercontent.com/201688/38307042-b547acae-3812-11e8-863c-a68b869176bb.png)

**Comment by samwiseg00** [comment]
After doing some research it does not look like you can put all discovered items into a single graph. The workaround now is to make the graph after the items have been discovered. 

It looks like this functionality will be in 4.0. According to the ticket below.
More info:
https://support.zabbix.com/browse/ZBXNEXT-927
